# Generated by Django 5.0.4 on 2024-05-01 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0010_alter_cpu_utilization_log_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpu_utilization',
            name='log_time',
        ),
    ]
